# nile.toml file generated for lasttrydep111 on 2023-10-31T13:42:50+05:30

app = "lasttrydep111"
id = "067514b8fbfb692e5ce0b48a594ff6bed6b897b0717156147efa4721b7816283e69a659ac5bd76095e141d53e50c96ce"

[build]
  builtin = "static react"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  external_port = 80
  http_checks = []
  internal_port = 3000
  protocol = "tcp"
  routing_policy = "Latency"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.limits]
    cpu = "1"
    memory = "256"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.requests]
    cpu = "0.5"
    memory = "128"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
