# nile.toml file generated for lasttry1 on 2023-10-26T19:14:20+05:30

app = "lasttry1"
id = "648b11c1508f50c35f0292686bb4b27a83dcec120607239a1ce901f6e7768cffdb16fb51c00a0ddb2f1b81763700ef00"

[build]
  builtin = "static react"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  external_port = 80
  http_checks = []
  internal_port = 3000
  protocol = "tcp"
  routing_policy = "Latency"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.limits]
    cpu = "1"
    memory = "256"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.requests]
    cpu = "0.5"
    memory = "128"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
