# nile.toml file generated for rkrkrkrk on 2023-10-04T20:42:39+05:30

app = "rkrkrkrk"
id = "131cb557a9f9dec4d360c9b52399541215b5bb7ff7b51eaebbbe27338c7f755d32f8d272be54e141000206fd1833d733"

[build]
  image = "nginx:latest"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  external_port = 80
  http_checks = []
  internal_port = 80
  protocol = "tcp"
  routing_policy = "Latency"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.limits]
    cpu = "1"
    memory = "256"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.requests]
    cpu = "0.5"
    memory = "128"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
