# nile.toml file generated for nifeactiontesting on 2023-08-29T19:15:59+05:30

app = "nifeactiontesting11"
id = "82adeeadb0d2453038b1e8d1888d1704a02de4d71ef49bda5d85d7bb3a54d05512da1fdadfbe89ec0ee946ed2129ed5a"

[build]
  image = "nife123/snake-node:deployment-74h031"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  external_port = 80
  http_checks = []
  internal_port = 4040
  protocol = "tcp"
  routing_policy = "Latency"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.limits]
    cpu = "1"
    memory = "256"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.requests]
    cpu = "0.5"
    memory = "128"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
